# Generated by Django 3.1.2 on 2020-10-14 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nick_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('portrait', models.ImageField(upload_to='picts\\portrait', verbose_name='portrait')),
                ('city', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('sign_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最后登陆时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.FileField(default='avatars/default.jpg', upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Pict',
            fields=[
                ('pict_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('love_num', models.CharField(max_length=30)),
                ('uploader_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('kind', models.ManyToManyField(related_name='pict_kind', to='Picts.Kind')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_date', models.DateTimeField(auto_now=True, verbose_name='收藏时间')),
                ('pict_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Picts.pict')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Picts.user')),
            ],
        ),
    ]
