# Generated by Django 3.1.2 on 2020-10-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pict',
            name='pic_url',
            field=models.ImageField(default='66', upload_to='background'),
        ),
    ]
