# Generated by Django 3.1.2 on 2020-10-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picts', '0002_pict_pic_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='pic_url',
            field=models.ImageField(default='66', upload_to='background/'),
        ),
    ]
