# Generated by Django 3.1.2 on 2020-10-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picts', '0003_auto_20201014_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='love_num',
            field=models.IntegerField(default=0),
        ),
    ]
