# Generated by Django 3.1.2 on 2020-10-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Picts', '0004_auto_20201015_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sign_time',
            new_name='c_time',
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(default='unknown', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
